language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hoopikhoop/docker-react -f Dockerfile.dev .Hoopikhoop/docker-react

script:
  - docker run -e CI=true hoopikhoop/docker-react npm run test
